# Change these first
owner: dev-yoonik # Your GitHub organization or username, where this repository lives
repo: yoonik-systems-status # The name of this repository
user-agent: $YV_USER_AGENT

sites:
  - name: Website
    url: https://www.youverse.id/
  - name: YouID
    url: https://kyc-web.youverse.id/
  - name: YouAuth API
    url: https://enroll.youverse.id/v4/api/health
  - name: YouFace API
    url: https://face.youverse.id/v3/api/health


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.youverse.id
  # baseUrl: /your-repo-name
  logoUrl: https://yk-website-images.s3.eu-west-1.amazonaws.com/logo.png
  favicon: https://yk-website-images.s3.eu-west-1.amazonaws.com/images/home/yk-favicon.png
  name: Youverse
  navbar:
    - title: Status
      href: /

i18n:
  footer: ''

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
