# Change these first
owner: dev-yoonik # Your GitHub organization or username, where this repository lives
repo: yoonik-systems-status # The name of this repository

sites:
  - name: YooniK Website
    url: https://www.yoonik.me/
  - name: YooniK SSO
    url: https://accounts.yoonik.me/health_check
  - name: YooniK Face API v2 - Main
    url: https://face.yoonik.me/v2/yoonik/health
  - name: YooniK Face API v2 - Workers
    url: https://face.yoonik.me/v2/yoonik/health-worker

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yoonik.me
  # baseUrl: /your-repo-name
  logoUrl: https://yk-website-images.s3.eu-west-1.amazonaws.com/logo.png
  favicon: https://yk-website-images.s3.eu-west-1.amazonaws.com/images/home/yk-favicon.png
  name: YooniK
  navbar:
    - title: Status
      href: /

i18n:
  footer: ''

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
